# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('image_name', models.CharField(max_length=20)),
                ('image_description', models.TextField(max_length=250)),
                ('image_category', models.ManyToManyField(to='gallery.Category')),
                ('image_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Location')),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
    ]
