# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190302_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.TextField(max_length=400),
        ),
    ]
